[book]
authors = ["k-nasa"]
language = "ja"
multilingual = false
src = "src"
title = "Asynchronous Programming in Rust"

[build]
create-missing = false

[preprocess.links]

[output.html]
git-repository-url = "https://github.com/k-nasa/async-book-ja"
git-repository-icon = "fa-github"
